name: aoc
description: Advent of Code 2023
version: 1.0.0
repository: https://github.com/bcsizmadia/aoc2023
publish_to: none

executables:
  new:

environment:
  sdk: ^3.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9

dependencies:
  dotenv: ^4.2.0
  http: ^1.1.2
